name: Collect GitHub Traffic

on:
  schedule:
    - cron: "0 2 * * *"   # every day
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  # This workflow contains a single job called "traffic"
  traffic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Fetch traffic via API
        run: |
          repos=(
            "soul-traveller/Argyll_Printer_Profiler"
            "soul-traveller/Toggle_Display_Profile"
            "soul-traveller/rectarg"
          )

          echo "[]" > traffic.json

          for repo in "${repos[@]}"; do
            echo "Fetching $repo"

            data=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.TRAFFIC_ACTION_TOKEN }}" \
              https://api.github.com/repos/$repo/traffic/clones)

            jq --arg repo "$repo" \
              '. + [{"repository": $repo, "clones": .}]' \
              traffic.json > tmp.json

            mv tmp.json traffic.json
          done

      - name: Save history
        run: |
          if [ -f history.json ]; then
            jq -s '.[0] + .[1]' history.json traffic.json > tmp.json
            mv tmp.json history.json
          else
            cp traffic.json history.json
          fi

      - name: Commit data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add history.json
          git commit -m "Update traffic history" || echo "No changes"
          git push
